// <auto-generated />
namespace ISR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_props_email1_mobile1_to_amail_mobile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_props_email1_mobile1_to_amail_mobile));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110559285_change_props_email1_mobile1_to_amail_mobile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
