//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISR.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISR.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید شده.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید درخواست.
        /// </summary>
        public static string AcceptRequest {
            get {
                return ResourceManager.GetString("AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های تایید شده توسط کارشناس بین الملل.
        /// </summary>
        public static string AcceptRequestByExpert {
            get {
                return ResourceManager.GetString("AcceptRequestByExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از تایید درخواست انتخابی اطمینان دارید ؟.
        /// </summary>
        public static string AcceptTitle {
            get {
                return ResourceManager.GetString("AcceptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما فعال نیست..
        /// </summary>
        public static string Account_Deactive {
            get {
                return ResourceManager.GetString("Account_Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با تشکر، حساب کاربری شما با موفقیت فعال گردید. لطفاً جهت ثبت درخواست وارد حساب کاربری خود شوید..
        /// </summary>
        public static string AccountActivated {
            get {
                return ResourceManager.GetString("AccountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل تمامی گزینه ها الزامی است.
        /// </summary>
        public static string All_Fields_Required {
            get {
                return ResourceManager.GetString("All_Fields_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه ثبت نام دانشجویان بین الملل.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربی.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی.
        /// </summary>
        public static string Bachelor {
            get {
                return ResourceManager.GetString("Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال تولد.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل تولد.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نابینا.
        /// </summary>
        public static string Blind {
            get {
                return ResourceManager.GetString("Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برادر.
        /// </summary>
        public static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت تغییرات.
        /// </summary>
        public static string btn_update_request {
            get {
                return ResourceManager.GetString("btn_update_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائیـــــــد.
        /// </summary>
        public static string btnAcceptRequest {
            get {
                return ResourceManager.GetString("btnAcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائیـــــــد.
        /// </summary>
        public static string btnConfirmCandidateField {
            get {
                return ResourceManager.GetString("btnConfirmCandidateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رشته.
        /// </summary>
        public static string btnDeleteCandidateField {
            get {
                return ResourceManager.GetString("btnDeleteCandidateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string btnFileUploadr {
            get {
                return ResourceManager.GetString("btnFileUploadr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد.
        /// </summary>
        public static string btnRejectRequest {
            get {
                return ResourceManager.GetString("btnRejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب رشته های مورددرخواست.
        /// </summary>
        public static string Candidate_Fields_List {
            get {
                return ResourceManager.GetString("Candidate_Fields_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته های منتخب.
        /// </summary>
        public static string CandidateFields {
            get {
                return ResourceManager.GetString("CandidateFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرزند.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته های قابل انتخاب.
        /// </summary>
        public static string Choosable_Fields {
            get {
                return ResourceManager.GetString("Choosable_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب رشته.
        /// </summary>
        public static string ChooseField {
            get {
                return ResourceManager.GetString("ChooseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته های انتخاب شده.
        /// </summary>
        public static string ChosenFields {
            get {
                return ResourceManager.GetString("ChosenFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیحی.
        /// </summary>
        public static string Christian {
            get {
                return ResourceManager.GetString("Christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تابعیت.
        /// </summary>
        public static string Citizenship {
            get {
                return ResourceManager.GetString("Citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل سکونت در کشور متبوع.
        /// </summary>
        public static string CitizenshipResidenceAddress {
            get {
                return ResourceManager.GetString("CitizenshipResidenceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل کار در کشور متبوع.
        /// </summary>
        public static string CitizenshipWorkPlaceAddress {
            get {
                return ResourceManager.GetString("CitizenshipWorkPlaceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش دانشگاهی.
        /// </summary>
        public static string Collage {
            get {
                return ResourceManager.GetString("Collage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانشکده.
        /// </summary>
        public static string College {
            get {
                return ResourceManager.GetString("College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلامت کامل.
        /// </summary>
        public static string CompleteHealth {
            get {
                return ResourceManager.GetString("CompleteHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید و ادامه.
        /// </summary>
        public static string ConfirmAndContinue {
            get {
                return ResourceManager.GetString("ConfirmAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل اطلاعات یکی از بخش های &quot;محل سکونت در ایران&quot; و یا &quot;محل سکونت در کشور متبوع&quot; الزامی می باشد.
        /// </summary>
        public static string ContactInfoForm_Help {
            get {
                return ResourceManager.GetString("ContactInfoForm_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی حقوق این سایت محفوظ و متعلق به واحد الکترونیکی دانشگاه آزاد اسلامی است..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فرزندان.
        /// </summary>
        public static string CountOfChildren {
            get {
                return ResourceManager.GetString("CountOfChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کشور .
        /// </summary>
        public static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور محل تحصیل.
        /// </summary>
        public static string CountryOfStudy {
            get {
                return ResourceManager.GetString("CountryOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string CountryTitle {
            get {
                return ResourceManager.GetString("CountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری خود را ایجاد کنید.
        /// </summary>
        public static string Create_Your_Account {
            get {
                return ResourceManager.GetString("Create_Your_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب کاربری.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در انجام عملیات.
        /// </summary>
        public static string Critical_Error {
            get {
                return ResourceManager.GetString("Critical_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع مورد درخواست.
        /// </summary>
        public static string Current_Level {
            get {
                return ResourceManager.GetString("Current_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناشنوا.
        /// </summary>
        public static string Deaf {
            get {
                return ResourceManager.GetString("Deaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل اخذ.
        /// </summary>
        public static string DegreePlace {
            get {
                return ResourceManager.GetString("DegreePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string DescriptionAboutDocument {
            get {
                return ResourceManager.GetString("DescriptionAboutDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  جزئیات مدارک.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیپلم.
        /// </summary>
        public static string Diploma {
            get {
                return ResourceManager.GetString("Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلول شنوایی.
        /// </summary>
        public static string DisabilityOfHearing {
            get {
                return ResourceManager.GetString("DisabilityOfHearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلول حرکتی.
        /// </summary>
        public static string DisabilityOfMovement {
            get {
                return ResourceManager.GetString("DisabilityOfMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلول گویایی.
        /// </summary>
        public static string DisabilityOfSpeech {
            get {
                return ResourceManager.GetString("DisabilityOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلول بینایی.
        /// </summary>
        public static string DisabilityOfVision {
            get {
                return ResourceManager.GetString("DisabilityOfVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مدرک .
        /// </summary>
        public static string Doc_Name {
            get {
                return ResourceManager.GetString("Doc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش.
        /// </summary>
        public static string Doc_Preview {
            get {
                return ResourceManager.GetString("Doc_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Doc_Status {
            get {
                return ResourceManager.GetString("Doc_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدرک.
        /// </summary>
        public static string Doc_Upload {
            get {
                return ResourceManager.GetString("Doc_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ادامه.
        /// </summary>
        public static string Doc_Upload_Btn {
            get {
                return ResourceManager.GetString("Doc_Upload_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گذرنامه / شماره کارت اقامت / شماره ملی.
        /// </summary>
        public static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارک بارگذاری شده.
        /// </summary>
        public static string DocsUploaded {
            get {
                return ResourceManager.GetString("DocsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکترا.
        /// </summary>
        public static string Doctorate {
            get {
                return ResourceManager.GetString("Doctorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مدرک.
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مدرک یا کد ملی.
        /// </summary>
        public static string DocumentNumberOrNationalCode {
            get {
                return ResourceManager.GetString("DocumentNumberOrNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مدرک.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- انتخاب کنید --.
        /// </summary>
        public static string Dropdown_Choose {
            get {
                return ResourceManager.GetString("Dropdown_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- تابعیت --.
        /// </summary>
        public static string Dropdown_Citizenship {
            get {
                return ResourceManager.GetString("Dropdown_Citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری با این آدرس ایمیل قبلاً ایجاد شده است. اگر رمز عبور خود را فراموش کرده اید از قسمت &lt;a href=&quot;{0}&quot;&gt;بازیابی رمز عبور&lt;/a&gt; وارد حساب کاربری خود شوید..
        /// </summary>
        public static string Duplicate_Email {
            get {
                return ResourceManager.GetString("Duplicate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تحصیلی.
        /// </summary>
        public static string EducationalInfo {
            get {
                return ResourceManager.GetString("EducationalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;direction: {1}&quot;&gt;ضمن خوش آمد گویی به شما دانشجوی محترم، حساب کاربری شما در سامانه ثبت نام دانشجویان بین الملل واحد الکترونیکی دانشگاه آزاد اسلامی با موفقیت ایجاد گردید. لطفاً جهت فعالسازی حساب کاربری خود، بر روی لینک زیر کلیک نمایید: &lt;br /&gt; {0} &lt;br /&gt; با تشکر &lt;br /&gt; واحد الکترونیکی دانشگاه آزاد اسلامی&lt;/div&gt;.
        /// </summary>
        public static string Email_Verification_Body {
            get {
                return ResourceManager.GetString("Email_Verification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال سازی حساب کاربری.
        /// </summary>
        public static string Email_Verification_Subject {
            get {
                return ResourceManager.GetString("Email_Verification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل مدیر اداره ثبت نام.
        /// </summary>
        public static string EnrollmentOfficeManagerPanel {
            get {
                return ResourceManager.GetString("EnrollmentOfficeManagerPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطلا در انجام عملیات.
        /// </summary>
        public static string ErrorInDurationOfOperation {
            get {
                return ResourceManager.GetString("ErrorInDurationOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های تائید شده توسط کارشناس بین الملل.
        /// </summary>
        public static string Ex_Accepted {
            get {
                return ResourceManager.GetString("Ex_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات اعضای خانواده یا افراد تحت تکفل.
        /// </summary>
        public static string FamilyAndChildren {
            get {
                return ResourceManager.GetString("FamilyAndChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات اعضای خانواده و معرف.
        /// </summary>
        public static string FamilyInfo {
            get {
                return ResourceManager.GetString("FamilyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعضای خانواده.
        /// </summary>
        public static string FamilyMember {
            get {
                return ResourceManager.GetString("FamilyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پدر.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مونث.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه رشته.
        /// </summary>
        public static string Field_Id {
            get {
                return ResourceManager.GetString("Field_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان رشته.
        /// </summary>
        public static string Field_Title {
            get {
                return ResourceManager.GetString("Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی.
        /// </summary>
        public static string FieldOfStudy {
            get {
                return ResourceManager.GetString("FieldOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشد jpeg یا jpg  فرمت فایل انتخابی تنها می تواند.
        /// </summary>
        public static string FileFormatIsInvalid_ErrorBody {
            get {
                return ResourceManager.GetString("FileFormatIsInvalid_ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل نامعتبر.
        /// </summary>
        public static string FileFormatIsInvalid_ErrorTitle {
            get {
                return ResourceManager.GetString("FileFormatIsInvalid_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و کلمه عبور را وارد نمایید..
        /// </summary>
        public static string Fill_Username_And_Password {
            get {
                return ResourceManager.GetString("Fill_Username_And_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل را وارد نمایید.
        /// </summary>
        public static string FillEmail {
            get {
                return ResourceManager.GetString("FillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های تائید نهایی شده توسط مدیر بین الملل.
        /// </summary>
        public static string FinalAcceptRequestByManager {
            get {
                return ResourceManager.GetString("FinalAcceptRequestByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های تائید اولیه شده توسط مدیر بین الملل.
        /// </summary>
        public static string FirstAcceptRequestByManager {
            get {
                return ResourceManager.GetString("FirstAcceptRequestByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را فراموش کرده اید؟.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پر کردن موارد ستاره دار اجباری می باشد.
        /// </summary>
        public static string FormValidation_ErrorBody {
            get {
                return ResourceManager.GetString("FormValidation_ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبار سنجی فرم.
        /// </summary>
        public static string FormValidation_ErrorTitle {
            get {
                return ResourceManager.GetString("FormValidation_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوست.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پدربزرگ.
        /// </summary>
        public static string GrandFather {
            get {
                return ResourceManager.GetString("GrandFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جد.
        /// </summary>
        public static string GrandFathersName {
            get {
                return ResourceManager.GetString("GrandFathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت هویت ویژه اتباع خارجی.
        /// </summary>
        public static string IdentityCardOfForeignCitizens {
            get {
                return ResourceManager.GetString("IdentityCardOfForeignCitizens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات اولیه.
        /// </summary>
        public static string InfoAdded {
            get {
                return ResourceManager.GetString("InfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال بررسی.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های در حال بررسی.
        /// </summary>
        public static string InProgressRequests {
            get {
                return ResourceManager.GetString("InProgressRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل کارشناس اداره بین الملل.
        /// </summary>
        public static string InternationalOfficeExpertPanel {
            get {
                return ResourceManager.GetString("InternationalOfficeExpertPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل مدیر اداره بین الملل.
        /// </summary>
        public static string InternationalOfficeManagerPanel {
            get {
                return ResourceManager.GetString("InternationalOfficeManagerPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا کلمه عبور صحیح نیست..
        /// </summary>
        public static string Invalid_Login {
            get {
                return ResourceManager.GetString("Invalid_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل معتبر نیست.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نامعتبر می باشد.
        /// </summary>
        public static string InvalidRequestType {
            get {
                return ResourceManager.GetString("InvalidRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه: در صورتی که مادر شما ایرانی باشد، این قسمت را تکمیل نمایید..
        /// </summary>
        public static string IranianMotherAlert {
            get {
                return ResourceManager.GetString("IranianMotherAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل سکونت در ایران.
        /// </summary>
        public static string IranResidenceAddress {
            get {
                return ResourceManager.GetString("IranResidenceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل کار در ایران.
        /// </summary>
        public static string IranWorkPlace {
            get {
                return ResourceManager.GetString("IranWorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسلام.
        /// </summary>
        public static string Islam {
            get {
                return ResourceManager.GetString("Islam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های رد شده توسط کارشناس بین الملل.
        /// </summary>
        public static string ISR_Expert_Reject {
            get {
                return ResourceManager.GetString("ISR_Expert_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل صدور.
        /// </summary>
        public static string IssuePlace {
            get {
                return ResourceManager.GetString("IssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیمی.
        /// </summary>
        public static string Jewish {
            get {
                return ResourceManager.GetString("Jewish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شغل.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاردانی.
        /// </summary>
        public static string Kardani {
            get {
                return ResourceManager.GetString("Kardani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ارشد ناپیوسته.
        /// </summary>
        public static string KarshenasiArshadNaPeivasteh {
            get {
                return ResourceManager.GetString("KarshenasiArshadNaPeivasteh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ارشد پیوسته.
        /// </summary>
        public static string KarshenasiArshadPeivasteh {
            get {
                return ResourceManager.GetString("KarshenasiArshadPeivasteh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ناپیوسته.
        /// </summary>
        public static string KarshenasiNaPeivasteh {
            get {
                return ResourceManager.GetString("KarshenasiNaPeivasteh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی پیوسته.
        /// </summary>
        public static string KarshenasiPeivasteh {
            get {
                return ResourceManager.GetString("KarshenasiPeivasteh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کردی.
        /// </summary>
        public static string Kurdish {
            get {
                return ResourceManager.GetString("Kurdish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string LANGUAGE_DIRECTION {
            get {
                return ResourceManager.GetString("LANGUAGE_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل کل در آخرین مقطع تحصیلی.
        /// </summary>
        public static string Last_Education_Average {
            get {
                return ResourceManager.GetString("Last_Education_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور اخذ آخرین مقطع تحصیلی.
        /// </summary>
        public static string Last_Education_Country {
            get {
                return ResourceManager.GetString("Last_Education_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اخذ آخرین مقطع تحصیلی.
        /// </summary>
        public static string Last_Education_Date {
            get {
                return ResourceManager.GetString("Last_Education_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخرین مدرک تحصیلی .
        /// </summary>
        public static string Last_Education_Degree {
            get {
                return ResourceManager.GetString("Last_Education_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی آخرین مقطع تحصیلی.
        /// </summary>
        public static string Last_Education_Field {
            get {
                return ResourceManager.GetString("Last_Education_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مقطع تحصیلی.
        /// </summary>
        public static string Last_Level {
            get {
                return ResourceManager.GetString("Last_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگ تردد خروجی مدت دار.
        /// </summary>
        public static string LimitedTransitCard {
            get {
                return ResourceManager.GetString("LimitedTransitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;0&quot;: &quot;-- انتخاب کنید --&quot;,
        ///    &quot;1&quot;: &quot;دیپلم&quot;,
        ///    &quot;2&quot;: &quot;پیش دانشگاهی&quot;,
        ///    &quot;3&quot;: &quot;کارشناسی&quot;,
        ///    &quot;4&quot;: &quot;کارشناسی ارشد&quot;,
        ///    &quot;5&quot;: &quot;دکتری&quot;
        ///}.
        /// </summary>
        public static string ListOfLevels {
            get {
                return ResourceManager.GetString("ListOfLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد حساب کاربری خود شوید.
        /// </summary>
        public static string Login_To_Your_Account {
            get {
                return ResourceManager.GetString("Login_To_Your_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود یا ثبت نام.
        /// </summary>
        public static string LoginOrRegister {
            get {
                return ResourceManager.GetString("LoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های تائید شده توسط مدیر اداره ثبت نام.
        /// </summary>
        public static string M_Enrollment_Accepted {
            get {
                return ResourceManager.GetString("M_Enrollment_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های رد شده توسط مدیر اداره ثبت نام.
        /// </summary>
        public static string M_Enrollment_Rejected {
            get {
                return ResourceManager.GetString("M_Enrollment_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های تائید نهایی شده توسط مدیر بین الملل.
        /// </summary>
        public static string M_Final_Accepted {
            get {
                return ResourceManager.GetString("M_Final_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های تائید اولیه شده توسط مدیر بین الملل.
        /// </summary>
        public static string M_First_Accepted {
            get {
                return ResourceManager.GetString("M_First_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست های رد شده توسط مدیر بین الملل.
        /// </summary>
        public static string M_Rejected {
            get {
                return ResourceManager.GetString("M_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذکر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تاهل.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاهل با همسر.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاهل دور از همسر.
        /// </summary>
        public static string Married_Away {
            get {
                return ResourceManager.GetString("Married_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ارشد.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دوم.
        /// </summary>
        public static string Middlename {
            get {
                return ResourceManager.GetString("Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل انتخابی حتما jpeg یا jpg باشد.
        /// </summary>
        public static string ModalFileFormat {
            get {
                return ResourceManager.GetString("ModalFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل انتخابی کمتر از دو مگابایت باشد.
        /// </summary>
        public static string ModalFileSize {
            get {
                return ResourceManager.GetString("ModalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مادر.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات مادر.
        /// </summary>
        public static string MothersInfo {
            get {
                return ResourceManager.GetString("MothersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مادر.
        /// </summary>
        public static string MothersName {
            get {
                return ResourceManager.GetString("MothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایرانی.
        /// </summary>
        public static string Nationatity_Iran {
            get {
                return ResourceManager.GetString("Nationatity_Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر ایرانی.
        /// </summary>
        public static string Nationatity_NoIran {
            get {
                return ResourceManager.GetString("Nationatity_NoIran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته ای یافت نشد.
        /// </summary>
        public static string No_Fields_Found {
            get {
                return ResourceManager.GetString("No_Fields_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسمی.
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد الکترونیکی دانشگاه آزاد اسلامی.
        /// </summary>
        public static string OrganizationTitle {
            get {
                return ResourceManager.GetString("OrganizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر نقص عضوها.
        /// </summary>
        public static string OtherDisabilities {
            get {
                return ResourceManager.GetString("OtherDisabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرنامه /کارت هویت / کارت امایش.
        /// </summary>
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;direction: {1}&quot;&gt;لطفاً از طریق لینک زیر وارد حساب کاربری خود شده و رمز عبور خود را بازیابی نمایید: &lt;br /&gt; {0} &lt;br /&gt; با تشکر &lt;br /&gt; واحد الکترونیکی دانشگاه آزاد اسلامی&lt;/div&gt;.
        /// </summary>
        public static string PasswordRecovery_EmailBody {
            get {
                return ResourceManager.GetString("PasswordRecovery_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل ثبت نشده است.
        /// </summary>
        public static string PasswordRecovery_NotFound {
            get {
                return ResourceManager.GetString("PasswordRecovery_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک بازیابی به آدرس ایمیل شما ارسال شد، لطفاً از طریق لینک ارسال شده وارد حساب خود شده و رمز عبور را بازیابی کنید..
        /// </summary>
        public static string PasswordRecovery_Sent {
            get {
                return ResourceManager.GetString("PasswordRecovery_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string PasswordReset_ChangePassword {
            get {
                return ResourceManager.GetString("PasswordReset_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        public static string PasswordReset_NewPassword {
            get {
                return ResourceManager.GetString("PasswordReset_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور جدید.
        /// </summary>
        public static string PasswordReset_NewPasswordRepeat {
            get {
                return ResourceManager.GetString("PasswordReset_NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید و تکرار آن یکسان نیست.
        /// </summary>
        public static string PasswordReset_NotMatch {
            get {
                return ResourceManager.GetString("PasswordReset_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور با موفقیت انجام شد.
        /// </summary>
        public static string PasswordReset_Success {
            get {
                return ResourceManager.GetString("PasswordReset_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتری حرفه ای.
        /// </summary>
        public static string PerfessionalDoctorate {
            get {
                return ResourceManager.GetString("PerfessionalDoctorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فردی و هویتی.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پرسنلی.
        /// </summary>
        public static string PersonalPicture {
            get {
                return ResourceManager.GetString("PersonalPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خود فرد.
        /// </summary>
        public static string PersonHimself {
            get {
                return ResourceManager.GetString("PersonHimself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتری.
        /// </summary>
        public static string Phd {
            get {
                return ResourceManager.GetString("Phd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ثابت.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت جسمانی.
        /// </summary>
        public static string PhysicalStatus {
            get {
                return ResourceManager.GetString("PhysicalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک.
        /// </summary>
        public static string PlaceNumber {
            get {
                return ResourceManager.GetString("PlaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش دانشگاهی.
        /// </summary>
        public static string PreUniversity {
            get {
                return ResourceManager.GetString("PreUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید اطلاعات.
        /// </summary>
        public static string PreviewAndConfirm {
            get {
                return ResourceManager.GetString("PreviewAndConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ اطلاعات.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرینت اطلاعات.
        /// </summary>
        public static string PrintDetails {
            get {
                return ResourceManager.GetString("PrintDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار آن یکسان نیست.
        /// </summary>
        public static string ReapeatPassword_Not_Match {
            get {
                return ResourceManager.GetString("ReapeatPassword_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف.
        /// </summary>
        public static string Recommender {
            get {
                return ResourceManager.GetString("Recommender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد معرف.
        /// </summary>
        public static string RecommenderCode {
            get {
                return ResourceManager.GetString("RecommenderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات معرف.
        /// </summary>
        public static string RecommenderInfo {
            get {
                return ResourceManager.GetString("RecommenderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفترچه پناهندگی.
        /// </summary>
        public static string RefugeeBooklet {
            get {
                return ResourceManager.GetString("RefugeeBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد شده.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست.
        /// </summary>
        public static string RejectRequest {
            get {
                return ResourceManager.GetString("RejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های رد شده توسط کارشناس بین الملل.
        /// </summary>
        public static string RejectRequestByExpert {
            get {
                return ResourceManager.GetString("RejectRequestByExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های رد شده توسط مدیر بین الملل .
        /// </summary>
        public static string RejectRequestByManager {
            get {
                return ResourceManager.GetString("RejectRequestByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از رد درخواست انتخابی اطمینان دارید ؟.
        /// </summary>
        public static string RejectTitle {
            get {
                return ResourceManager.GetString("RejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام گرددید.
        /// </summary>
        public static string RelatedPersonAdded {
            get {
                return ResourceManager.GetString("RelatedPersonAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبت.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دین.
        /// </summary>
        public static string Relegion {
            get {
                return ResourceManager.GetString("Relegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ درخواست.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات درخواست.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه درخواست.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره درخواست.
        /// </summary>
        public static string RequestNo {
            get {
                return ResourceManager.GetString("RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه درخواست ها.
        /// </summary>
        public static string RequestsHistory {
            get {
                return ResourceManager.GetString("RequestsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست ها.
        /// </summary>
        public static string RequestStatusLabel {
            get {
                return ResourceManager.GetString("RequestStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ویرایش با موفقیت انجام گرددید.
        /// </summary>
        public static string RequestUpdated {
            get {
                return ResourceManager.GetString("RequestUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی انتخاب موارد ستاره دار اجباری می باشد.
        /// </summary>
        public static string RequiredField_Astericks {
            get {
                return ResourceManager.GetString("RequiredField_Astericks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی رشته.
        /// </summary>
        public static string SearchForField {
            get {
                return ResourceManager.GetString("SearchForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تابعیت دوم.
        /// </summary>
        public static string SecondCitizenship {
            get {
                return ResourceManager.GetString("SecondCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدا شده.
        /// </summary>
        public static string Separated {
            get {
                return ResourceManager.GetString("Separated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمن خوش آمد گویی به شما دانشجوی محترم، حساب کاربری شما با موفقیت ایجاد گردید. لطفاً با مراجعه به ایمیل خود و کلیک بر روی لینک فعالسازی، وارد حساب کاربری خود شوید..
        /// </summary>
        public static string Signup_Successfull {
            get {
                return ResourceManager.GetString("Signup_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجرد.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواهر.
        /// </summary>
        public static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل انتخابی باید کمتر از یک مگابایت باشد.
        /// </summary>
        public static string SizeOfFileIsInvalid_ErrorBody {
            get {
                return ResourceManager.GetString("SizeOfFileIsInvalid_ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل نا معتبر.
        /// </summary>
        public static string SizeOfFileIsInvalid_ErrorTitle {
            get {
                return ResourceManager.GetString("SizeOfFileIsInvalid_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتری تخصص.
        /// </summary>
        public static string SpecialDoctorate {
            get {
                return ResourceManager.GetString("SpecialDoctorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همسر.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بررسی.
        /// </summary>
        public static string Status_Alaki_Text {
            get {
                return ResourceManager.GetString("Status_Alaki_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیابان و کوچه.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دانشجویی.
        /// </summary>
        public static string StudentCode {
            get {
                return ResourceManager.GetString("StudentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دانشجو.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملیت.
        /// </summary>
        public static string StudentNationality {
            get {
                return ResourceManager.GetString("StudentNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترم.
        /// </summary>
        public static string TermsLable {
            get {
                return ResourceManager.GetString("TermsLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایران، تهران.
        /// </summary>
        public static string TextAddrressInEmail {
            get {
                return ResourceManager.GetString("TextAddrressInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;پوهنتون آزاد اسلامی &lt;br /&gt;&lt;span style=&quot;font-size:30px&quot;&gt; واحد الکترونیکی&lt;/span&gt; &lt;/span&gt;.
        /// </summary>
        public static string TextBesideImageInEmail {
            get {
                return ResourceManager.GetString("TextBesideImageInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با ما در ارتباط باشید..
        /// </summary>
        public static string TextCantactUsInEmail {
            get {
                return ResourceManager.GetString("TextCantactUsInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل خود را از طریق لینک زیر تایید کنید.
        /// </summary>
        public static string TextConfirmationEmail {
            get {
                return ResourceManager.GetString("TextConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با سلام جناب آقای /سرکار خانوم.
        /// </summary>
        public static string TextHelloInEmail {
            get {
                return ResourceManager.GetString("TextHelloInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کسب معلومات بیشتر در مورد نحوه تقاضا برای مقطع لیسانس و ماستری ، لطفا از لینک های زیر استفاده نمایید..
        /// </summary>
        public static string TextHepleLinksInEmail {
            get {
                return ResourceManager.GetString("TextHepleLinksInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اداره بین الملل.
        /// </summary>
        public static string TextInternationOfficeInEmail {
            get {
                return ResourceManager.GetString("TextInternationOfficeInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International@iauec.ac.ir.
        /// </summary>
        public static string TextIRegLink {
            get {
                return ResourceManager.GetString("TextIRegLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وب سایت دانشگاه.
        /// </summary>
        public static string TextIregUrlInEmail {
            get {
                return ResourceManager.GetString("TextIregUrlInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ایمیل از پوهنتون آزاد اسلامی  واحد الکترونیکی جهت اطلاع  شما ارسال شده است. لطفا به این آدرس ایمیل پاسخ ندهید..
        /// </summary>
        public static string TextNoteInEmail {
            get {
                return ResourceManager.GetString("TextNoteInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string TextPhoneInEmail {
            get {
                return ResourceManager.GetString("TextPhoneInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوهنتون آزاد اسلامی واحد الکترونیکی.
        /// </summary>
        public static string TextPohentenInEmail {
            get {
                return ResourceManager.GetString("TextPohentenInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر رمز عبور خود را فراموش کردید می توانید آن را&lt;strong&gt;&lt;a href=&quot;#&quot;&gt; بازیابی&lt;/a&gt;&lt;/strong&gt; نمایید.  .
        /// </summary>
        public static string TextRecoveryPasswordInEmail {
            get {
                return ResourceManager.GetString("TextRecoveryPasswordInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشکر برای اقدام شما برای ثبت نام در پوهنتون آزاد اسلامی واحد الکترونیکی.
        /// </summary>
        public static string TextThanksInEmail {
            get {
                return ResourceManager.GetString("TextThanksInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری شما.
        /// </summary>
        public static string TextUserNameIEmail {
            get {
                return ResourceManager.GetString("TextUserNameIEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام کاربری خود را جهت ورود به سامانه انلاین و ادامه ثبت نام بخاطر بسپارید.
        /// </summary>
        public static string TextUsernameIsNecessaryInEmail {
            get {
                return ResourceManager.GetString("TextUsernameIsNecessaryInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق پستی.
        /// </summary>
        public static string TextZipCodeInEmail {
            get {
                return ResourceManager.GetString("TextZipCodeInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل کل.
        /// </summary>
        public static string TotalAverage {
            get {
                return ResourceManager.GetString("TotalAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترکی.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ازدواج.
        /// </summary>
        public static string TypeOfMarriage {
            get {
                return ResourceManager.GetString("TypeOfMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دانشگاه.
        /// </summary>
        public static string UniversityName {
            get {
                return ResourceManager.GetString("UniversityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string UnKnown {
            get {
                return ResourceManager.GetString("UnKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیررسمی.
        /// </summary>
        public static string Unofficial {
            get {
                return ResourceManager.GetString("Unofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدرک کارشناسی برای مقطع انتخابی الزامی می باشد.
        /// </summary>
        public static string ValidationMessage_BachelorDocIsRequired {
            get {
                return ResourceManager.GetString("ValidationMessage_BachelorDocIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع جاری انتخاب نشده است.
        /// </summary>
        public static string ValidationMessage_CurrentLevel {
            get {
                return ResourceManager.GetString("ValidationMessage_CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدرک دیپلم برای مقطع انتخابی الزامی می باشد.
        /// </summary>
        public static string ValidationMessage_DiplomaDocIsRequired {
            get {
                return ResourceManager.GetString("ValidationMessage_DiplomaDocIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مدرک تحصیلی انتخاب نشده است.
        /// </summary>
        public static string ValidationMessage_LastEducationDegree {
            get {
                return ResourceManager.GetString("ValidationMessage_LastEducationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدرک کارشناسی ارشد برای مقطع انتخابی الزامی می باشد.
        /// </summary>
        public static string ValidationMessage_MasterDocIsRequired {
            get {
                return ResourceManager.GetString("ValidationMessage_MasterDocIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدرک گذرنامه الزامی می باشد.
        /// </summary>
        public static string ValidationMessage_PassportDocIsRequired {
            get {
                return ResourceManager.GetString("ValidationMessage_PassportDocIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدرک عکس پرسنلی الزامی می باشد.
        /// </summary>
        public static string ValidationMessage_PersonalPictureDocIsRequired {
            get {
                return ResourceManager.GetString("ValidationMessage_PersonalPictureDocIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جانباز.
        /// </summary>
        public static string Veteran {
            get {
                return ResourceManager.GetString("Veteran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیوه.
        /// </summary>
        public static string Widow {
            get {
                return ResourceManager.GetString("Widow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل کتبی.
        /// </summary>
        public static string WrittenAverage {
            get {
                return ResourceManager.GetString("WrittenAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعالسازی صحیح نیست..
        /// </summary>
        public static string WrongHash {
            get {
                return ResourceManager.GetString("WrongHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زرتشتی.
        /// </summary>
        public static string Zoroastrian {
            get {
                return ResourceManager.GetString("Zoroastrian", resourceCulture);
            }
        }
    }
}
